import ToasterProvider from "./Providers/toaster.provider";
import ClientOnly from "./components/ClientOnly";
import Models from "./components/Models/Models";
import RegisterModel from "./components/Models/RegisterModel";
import Navbar from "./components/Navbar/Navbar";
import "./globals.css";
import { Nunito } from "next/font/google";

const font = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <ToasterProvider />
          <Navbar />
          <RegisterModel />
        </ClientOnly>
        {children}
      </body>
    </html>
  );
}
